### ISSUE TITLE
slightly brighter background colour

### ISSUE THREAD

**Issue by RafaelCz** [josa42/atom-smyck#4]
hukl, the original creator of SMYCK, changed the default background colour from 1b1b1b to 242424, and [later to 282828](https://github.com/hukl/Smyck-Color-Scheme/commit/66dcf7bfec9a381b29ce8e78a5398b9c2a482e9a). 
It would be nice to have a matching background colour in Atom as well.

**Comment by josa42** [comment]
This syntax theme is converted of the Smyck Textmate / Sublime Text theme [Smyck.tmTheme](https://github.com/hukl/Smyck-Color-Scheme/blob/master/Smyck.tmTheme#L17), which has #1B1B1B as background color.
